### Relu

In [2]:
import torch
import torch.nn as nn

class ReLU(nn.Module):
    def __init__(self):
        super(ReLU, self).__init__()

    def forward(self, x):
        return torch.max(x, torch.tensor(0.0))

# Example usage
relu = ReLU()
x = torch.tensor([-1.0, 0.0, 1.0, 2.0])
output = relu(x)
print(output)  # Output: tensor([0., 0., 1., 2.])

tensor([0., 0., 1., 2.])


### Sigmoid

In [3]:
class Sigmoid(nn.Module):
    def __init__(self):
        super(Sigmoid, self).__init__()

    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

# Example usage
sigmoid = Sigmoid()
output = sigmoid(x)
print(output)  # Output: tensor([0.2689, 0.5000, 0.7311, 0.8808])

tensor([0.2689, 0.5000, 0.7311, 0.8808])


### SoftMax

In [ ]:
class Softmax(nn.Module):
    def __init__(self, dim=-1):
        super(Softmax, self).__init__()
        self.dim = dim

    def forward(self, x):
        # torch.max(x, dim=-1, keepdim=True)[0] is used to ensure numerical stability by subtracting the maximum value from x before exponentiation.
        # torch.max() will return a tuple (values, indices), and we only need the values for the softmax calculation, hence [0] is used to extract the values.
        max_x = torch.max(x, dim=self.dim, keepdim=True)[0]
        sum_exp = torch.sum(torch.exp(x - max_x), dim=self.dim, keepdim=True)
        return torch.exp(x - max_x) / sum_exp

# Example usage
softmax = Softmax(dim=0)
x = torch.tensor([1.0, 2.0, 3.0])
# x = torch.tensor([1.0, 2.0, 1e9])  # To demonstrate numerical stability
output = softmax(x)
print(output)  # Output: tensor([0.0900, 0.2447, 0.6652])

tensor([0., 0., 1.])


### SiLU

In [ ]:
# 作为单独函数
def silu(x):
    return x * torch.sigmoid(x)

# 或使用PyTorch的内置函数
# F.silu(x)

# 作为层实现
class SiLU(nn.Module):
    def forward(self, x):
        return x * torch.sigmoid(x)